-- Extracted from flowdefs/LocationStream/13_ddl.sql (STATS table only)
CREATE TABLE IF NOT EXISTS {{ database }}.{{ schema_prefix }}METRICS.STATS (
	ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 ORDER,
	JOBID VARCHAR(16777216),
	JOBTYPE VARCHAR(16777216),
	STATNAME VARCHAR(16777216),
	STATDESC VARCHAR(16777216),
	AGGTYPE VARCHAR(16777216),
	STATVALUE FLOAT,
	INSERTEDDATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ(9),
	EXTRADETAILS OBJECT
);
